name: Fibonacci Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fibonacci-job:
    runs-on: ubuntu-latest

    steps:
      # 1. Reponun checkout işlemi
      - name: Check out the repository
        uses: actions/checkout@v2

      # 2. Python'ı kuruyoruz
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # 3. Gerekli bağımlılıkları kuruyoruz
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Eğer başka bir bağımlılık varsa requirements.txt kullanabilirsiniz

      # 4. Fibonacci fonksiyonunu test eden Python scriptini çalıştırıyoruz
      - name: Run Fibonacci test
        run: |
          echo 'def fibonacci(n):' > fibonacci_test.py
          echo '    fibonacci_dizisi = [0, 1]' >> fibonacci_test.py
          echo '    for i in range(2, n):' >> fibonacci_test.py
          echo '        sonraki = fibonacci_dizisi[-1] + fibonacci_dizisi[-2]' >> fibonacci_test.py
          echo '        fibonacci_dizisi.append(sonraki)' >> fibonacci_test.py
          echo '    return fibonacci_dizisi' >> fibonacci_test.py
          echo 'print(fibonacci(10))' >> fibonacci_test.py
          python fibonacci_test.py  # Fibonacci fonksiyonunu çalıştırıyoruz

      # 5. Sonuçları kontrol ediyoruz
      - name: Check output
        run: |
          if ! python fibonacci_test.py | grep -q "55"; then
            echo "Fibonacci output is incorrect!";
            exit 1;
          fi
          echo "Fibonacci test passed!"
