name: Fibonacci Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fibonacci-job:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Run Fibonacci test
        run: |
          echo 'def fibonacci(n):' > fibonacci_test.py
          echo '    fibonacci_dizisi = [0, 1]' >> fibonacci_test.py
          echo '    for i in range(2, n):' >> fibonacci_test.py
          echo '        sonraki = fibonacci_dizisi[-1] + fibonacci_dizisi[-2]' >> fibonacci_test.py
          echo '        fibonacci_dizisi.append(sonraki)' >> fibonacci_test.py
          echo '    return fibonacci_dizisi' >> fibonacci_test.py
          echo 'print(fibonacci(10))' >> fibonacci_test.py

      - name: Check output
        run: |
          result=$(python fibonacci_test.py)
          echo "Output: $result"
          if [[ "$result" != *"34"* ]]; then
            echo "Fibonacci çıktısı yanlış!";
            exit 1;
          fi
          echo "Fibonacci test edildi!"
